### ISSUE TITLE
Add Git tags

### ISSUE THREAD

**Issue by ehmicky** [MarkTiedemann/node-latest#2]
Hi and thanks for this project.

Would it be possible to add Git tags? When added this will automatically create GitHub releases. GitHub releases are nice because they allow users being notified of new releases using a RSS reader.

Tools like [`release-it`](https://github.com/webpro/release-it) can be used to automate this.

**Comment by MarkTiedemann** [comment]
Hi @ehmicky, I'm not using this project anymore so it is not actively maintained. Please feel free to open PRs to add things that you consider missing; I'll still review and merge.

**Comment by ehmicky** [comment]
Hi @MarkTiedemann if this is not maintained anymore, I will create my own module instead. Thanks!

**Comment by MarkTiedemann** [comment]
Sure. If you want, I can transfer ownership of this GitHub repo and the npm package to you.

**Comment by ehmicky** [comment]
No thanks I think I will start from scratch, because the logic is small enough.

**Comment by MarkTiedemann** [comment]
Alright, fair enough.

Once you've created the module, please let me know so I can deprecate this and link to yours.

Thanks!
